trigger: none
pr: none
name: 1.0.$(Build.BuildId)

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  dotNetVersion: 'net9.0'
  appPackageId: '{app-id-goes-here}'
  baseVersion: '1.0'
  projects: |
    Client/FarmApp.Mobile/FarmApp.Mobile.csproj
    Client/Library/Xamarin.Maplibre.Android/Xamarin.Maplibre.Android.csproj
    Client/Library/ReferenceBindings/Com.Mapbox.Mapboxsdk.Mapbox.Android.Gestures/Com.Mapbox.Mapboxsdk.Mapbox.Android.Gestures.csproj
    Client/Library/ReferenceBindings/Org.Maplibre.Gl.Android.Sdk.Geojson/Org.Maplibre.Gl.Android.Sdk.Geojson.csproj
    Client/Library/ReferenceBindings/Org.Maplibre.Gl.Android.Sdk.Turf/Org.Maplibre.Gl.Android.Sdk.Turf.csproj
    FarmApp.Shared\FarmApp.Shared.csproj
    
steps:

  - task: UseDotNet@2
    displayName: 'install .net 9.0 sdk'
    inputs:
      packageType: 'sdk'
      version: '9.0.x'

  - task: Bash@3
    displayName: 'install maui'
    inputs:
      targetType: 'inline'
      script: |
        dotnet workload install maui 

  - task: Bash@3
    displayName: 'set app version'
    inputs:
      targetType: 'inline'
      script: |
        sed -i '' "s|<ApplicationVersion>.*</ApplicationVersion>|<ApplicationVersion>$(baseVersion).$(Build.BuildId)</ApplicationVersion>|" Client/FarmApp.Mobile/FarmApp.Mobile.csproj
        sed -i '' "s|<ApplicationDisplayVersion>.*</ApplicationDisplayVersion>|<ApplicationDisplayVersion>$(baseVersion).$(Build.BuildId)</ApplicationDisplayVersion>|" Client/FarmApp.Mobile/FarmApp.Mobile.csproj

  - task: android-manifest-version@1
    displayName: 'android bundle version'
    inputs:
      sourcePath: 'Client/FarmApp.Mobile/Platforms/Android/AndroidManifest.xml'
      versionCodeOption: 'buildid'
      versionCode: '$(Build.BuildId)'
      versionCodeOffset: '1000'
      versionName: '$(baseVersion).$(Build.BuildId)'
      printFile: true
      
  - task: DownloadSecureFile@1
    name: downloadKeystore
    inputs:
      secureFile: 'app.keystore'

  - task: Bash@3
    displayName: 'build android app (signed)'
    inputs:
      targetType: 'inline'
      script: | 
          dotnet publish Client/FarmApp.Mobile/FarmApp.Mobile.csproj \
            -f $(dotNetVersion)-android \
            -c Release \
            /p:AndroidSigningKeyStore="$(downloadKeystore.secureFilePath)" \
            /p:AndroidSigningKeyAlias="$(AndroidSigningKeyAlias)" \
            /p:AndroidSigningStorePass="$(AndroidSigningStorePass)" \
            /p:AndroidSigningKeyPass="$(AndroidSigningKeyPass)"

  - script: |
      find Client/FarmApp.Mobile/bin/Release/$(dotNetVersion)-android/publish -type f
    displayName: 'print publish folder'

  - task: CopyFiles@2
    displayName: 'copy android files'
    inputs:
      Contents: |
        Client/FarmApp.Mobile/bin/Release/$(dotNetVersion)-android/publish/$(appPackageId)-Signed.aab
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'make $(appPackageId)-Signed.aab downloadable'
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/Client/FarmApp.Mobile/bin/Release/$(dotNetVersion)-android/publish/$(appPackageId)-Signed.aab
      artifactName: '$(appPackageId)-Signed.aab'
      publishLocation: 'Container'

  - script: |
      find $(build.ArtifactStagingDirectory) -type f
    displayName: 'print build.ArtifactStagingDirectory'

  - task: GooglePlayRelease@4
    displayName: 'send app to GooglePlay'
    inputs:
      serviceConnection: 'google-play-service-connection'
      applicationId: '$(appPackageId)'
      action: 'MultiApkAab'
      bundleFiles: 'Client/FarmApp.Mobile/bin/Release/$(dotNetVersion)-android/publish/$(appPackageId)-Signed.aab'
      track: 'internal'
      isDraftRelease: true
