<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFrameworks>net9.0-android;net9.0-ios;</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <RootNamespace>FarmApp.Mobile</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableDefaultCssItems>false</EnableDefaultCssItems>

        <ApplicationTitle>Farm App</ApplicationTitle>
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Debug'">
        <AndroidPackageFormat>apk</AndroidPackageFormat>
    </PropertyGroup>

    <PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
        <ApplicationId>{app-id-goes-here}</ApplicationId>
        <AndroidPackageFormat>aab</AndroidPackageFormat>
        <AndroidKeyStore>True</AndroidKeyStore>
        <AndroidCreatePackagePerAbi>True</AndroidCreatePackagePerAbi>
    </PropertyGroup>

    <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
        <ApplicationId>{app-id-goes-here}</ApplicationId>
        <EnableCodeSigning>true</EnableCodeSigning>
        <CodesignRequireProvisioningProfile>true</CodesignRequireProvisioningProfile>
        <DisableCodesignVerification>true</DisableCodesignVerification>
    </PropertyGroup>

    <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
        <ApplicationId>{app-id-goes-here}</ApplicationId>
        <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
        <ArchiveOnBuild>true</ArchiveOnBuild>
        <MtouchLink>SdkOnly</MtouchLink>
    </PropertyGroup>

    <ItemGroup>
        <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#123f44"/>
        <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#123f44" BaseSize="215,79" />
        <MauiImage Include="Resources\Images\*" />
        <MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />
        <MauiFont Include="Resources\Fonts\*" />
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="9.0.51" />
        <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.51" />
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.51" />

        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.7" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.7" />

        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.7" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />

        <PackageReference Include="CommunityToolkit.Maui" Version="11.1.0" />
        <PackageReference Include="CommunityToolkit.Maui.Core" Version="11.1.0" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
        <PackageReference Include="Xamarin.AndroidX.Core" Version="1.16.0.2" />
        <PackageReference Include="Xamarin.AndroidX.Collection" Version="1.5.0.2" />
        <PackageReference Include="Xamarin.AndroidX.Collection.Ktx" Version="1.5.0.2" />
        <PackageReference Include="Xamarin.AndroidX.Activity" Version="1.10.1.2" />
        <PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.10.1.2" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.9.1" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx" Version="2.9.1" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.9.1" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.9.1" />
        <PackageReference Include="Xamarin.AndroidX.Fragment" Version="1.8.8" />
        <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.8.8" />
        <PackageReference Include="Xamarin.AndroidX.SavedState" Version="1.3.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\FarmApp.Shared\FarmApp.Shared.csproj" />
        <ProjectReference Include="..\MaplibreNative\Maplibre.Maui\Maplibre.Maui.csproj" />
    </ItemGroup>

</Project>
